### ISSUE TITLE
No permissions to create/push to new branch

### ISSUE THREAD

**Issue by catherynl** [chrisstef/saas-marketing-template#11]
I tried to make a new branch & PR for a really simple change, but ran into this error:
```
remote: Permission to chrisstef/saas-marketing-template.git denied to catherynl.
fatal: unable to access 'https://github.com/chrisstef/saas-marketing-template.git/': The requested URL returned error: 403
```
I don't think it's a personal access token issue since I'm able to contribute to other repos.

**Comment by chrisstef** [comment]
A 403 code is "Forbidden". The server saw your request and refused it. Do you have permission to push to that repository?
Try `git remote -v` to double check first and it might need to connect with SSH.
